### ISSUE TITLE
Add WP-CLI support

### ISSUE THREAD

**Issue by grappler** [chrisberthe/wordpress-database-reset#13]
I would like to work to add WP-CLI support. To be able to do so the `wp_reset_init()` function will need to split up. I am thinking of splitting it into two section.
1. Function needed when running from wp-admin
2. Function that resets the tables.

http://wordpress.stackexchange.com/questions/162132/how-to-create-a-wp-cli-command-with-post/

**Comment by chrisberthe** [comment]
Hi @grappler, were you ever able to look into this? I'm thinking about getting back into this issue and refactoring completely.

**Comment by grappler** [comment]
Hey :smile: No, I have been too busy. It might be best to refactor it completely. Keep me updated. I can try and help if you need some.

**Comment by chrisberthe** [comment]
Hi @grappler, I've been able to allocate some time the last 2-3 weeks to rewriting the plugin code from scratch. Apart from the full re-write, I was also able to implement WP-CLI. You can find it on https://github.com/chrisberthe/wordpress-database-reset/tree/wp-cli.

Would greatly appreciate any feedback on the quality of the code, any recommendations and if you can test it.

**Comment by grappler** [comment]
@chrisberthe Sorry for the delayed reply. I did not have time before. it seems to work fine. I was not able to work out how the `reactivate` option was supposed to work.

it would be also good to add a inline notice mentioning that the `reactivate` worked so to give some feedback.

**Comment by chrisberthe** [comment]
Getting issues with the CLI and if passing `reactivate` to the command. For sure has something to do with: #16

**Comment by chrisberthe** [comment]
@grappler Should be good now, thanks.
