### ISSUE TITLE
Resetting the options table no longer works properly

### ISSUE THREAD

**Issue by chrisberthe** [chrisberthe/wordpress-database-reset#16]
The `options` table cannot be reset properly (definitely messed something up during the refactoring process). To replicate: activate the plugin, select the `options` table, reset it, refresh the page and you'll see the database reset plugin is no longer activated.

Also, this applies to any settings that options relates to, for instance: setting WordPress to a different theme or activating any other plugins... they won't be preserved even when selecting "Reactivate current theme and plugins after reset?"

**Comment by grappler** [comment]
It works now :smile:
