### ISSUE TITLE
Plugin disabled after update

### ISSUE THREAD

**Issue by grappler** [chrisberthe/wordpress-database-reset#17]
The change of `wp-reset.php` to `init.php` will cause the plugin to be disabled when the users update the plugin. The reason is that WordPress saves the files name and the directory name to the activated plugins. In this case `wordpress-database-reset/wp-reset.php`.

**Comment by chrisberthe** [comment]
Best solution I guess would be to remove `init.php` altogether and rename it back. I wasn't aware of this, so thank you.

Will update shortly.
