### ISSUE TITLE
Rename `theme_data` functions and variables

### ISSUE THREAD

**Issue by grappler** [chrisberthe/wordpress-database-reset#18]
There are a few functions and variables in `class-db-resetter.php` that are classified as `theme_data` which is not entirely correct as it also contains activated plugin data too.

**Comment by chrisberthe** [comment]
Yeah, perhaps not the best name.

I tried to combine plugin data with the theme data since the same types of functions are being called on them. Have an idea how you'd like to refactor this?

**Comment by grappler** [comment]
What about renaming it to `theme_plugin_data`?

**Comment by chrisberthe** [comment]
Cool.
