### ISSUE TITLE
Database reset does not remove custom tables

### ISSUE THREAD

**Issue by chrisberthe** [chrisberthe/wordpress-database-reset#19]
We should have a way to list all tables within the database, instead of just the default WordPress tables. However, I'm pretty sure this will cause several complex problems:
1. Custom plugin tables within the database have no way of being reset - just dropped.
2. Say for instance, a user has WooCommerce installed, and decides to reset one of their multiple tables, what to do?
3. By default the theme and plugin data is reactivated, so say a user decides to reset all WooCommerce, but does not deactivate the plugins, the WooCommerce plugin won't be functional.

**Comment by codekraft-studio** [comment]
It will be useful in some cases if you can TRUNCATE some tables, even the custom ones, like the ones made by other plugins, with the `reset` command.
Obviously with some **warnings** before the action, something like: "this may cause the plugin malfunction, be sure of what you are doing" :smiley: 

This will skip the whole phpMyAdmin / mysql -u ... .."use ...; TRUNCATE ...;" process
