### ISSUE TITLE
GitHub repo maintance

### ISSUE THREAD

**Issue by grappler** [chrisberthe/wordpress-database-reset#20]
You should update the project URL to http://wordpress.org/plugins/wordpress-database-reset/ excluding extend. Maybe also tag the releases on GitHub. :smile:

**Comment by chrisberthe** [comment]
You mean the project URL within the readme?

**Comment by grappler** [comment]
I meant on the GitHub page.
![image](https://cloud.githubusercontent.com/assets/1785641/10124453/aa4da39a-6555-11e5-8775-38faf6d164b2.png)
It is just a small thing :smile:

**Comment by chrisberthe** [comment]
Ha ha, okay updated the URL :smiley: Will get onto the tags eventually.

**Comment by chrisberthe** [comment]
Updated :metal:
